MVCApplicationFramework.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCApplicationFramework.WebUI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVCApplicationFramework.WebUI/Controllers/UserManagerController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using MVCApplicationFramework.Entities;
using Newtonsoft.Json;

namespace MVCApplicationFramework.WebUI.Controllers
{
    public class UserManagerController : Controller
    {
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger
               (System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public ActionResult Index()
        {
            using (var client = new HttpClient())
            {
                var response = client.GetAsync(ConfigurationManager.AppSettings["WebAPIBaseURL"] + "UserManager/GetUserList").Result;

                if (response.IsSuccessStatusCode && response.StatusCode == HttpStatusCode.OK)
                {
                    var apiResponseObject = JsonConvert.DeserializeObject<APIResponse>(response.Content.ReadAsStringAsync().Result);
                    if (apiResponseObject.MessageType == EnumMessageType.OPERATION_SUCCESS)
                    {
                        var users = JsonConvert.DeserializeObject<List<User>>(apiResponseObject.Data[0].ToString());
                        return View(users);
                    }
                    else
                    {
                        throw new Exception(apiResponseObject.Exception);
                    }
                }
                else
                {
                    log.Error("Error StatusCode:" + response.StatusCode.ToString() + " - " + response.ReasonPhrase);
                    throw new Exception(response.StatusCode.ToString());
                }
            }
        }

        public ActionResult Edit(int Id)
        {
            using (var client = new HttpClient())
            {
                var response = client.GetAsync(ConfigurationManager.AppSettings["WebAPIBaseURL"] + "UserManager/GetUserByID?userId=" + Convert.ToString(Id)).Result;

                if (response.IsSuccessStatusCode && response.StatusCode == HttpStatusCode.OK)
                {
                    var apiResponseObject = JsonConvert.DeserializeObject<APIResponse>(response.Content.ReadAsStringAsync().Result);
                    if (apiResponseObject.MessageType == EnumMessageType.OPERATION_SUCCESS)
                    {
                        var user = JsonConvert.DeserializeObject<Entities.User>(apiResponseObject.Data[0].ToString());
                        return View("Edit", user);
                    }
                    else
                    {
                        throw new Exception(apiResponseObject.Exception);
                    }
                }
                else
                {
                    log.Error("Error StatusCode:" + response.StatusCode.ToString() + " - " + response.ReasonPhrase);
                    throw new Exception(response.StatusCode.ToString());
                }
            }
        }

        [HttpPost]
        public ActionResult Edit(Entities.User model)
        {
            using (var client = new HttpClient())
            {
                var response = client.PostAsync(ConfigurationManager.AppSettings["WebAPIBaseURL"] + "UserManager/Save", new StringContent(JsonConvert.SerializeObject(model))).Result;

                if (response.IsSuccessStatusCode && response.StatusCode == HttpStatusCode.OK)
                {
                    var apiResponseObject = JsonConvert.DeserializeObject<APIResponse>(response.Content.ReadAsStringAsync().Result);
                    if (apiResponseObject.MessageType == EnumMessageType.OPERATION_SUCCESS)
                    {
                       
                        return View("Index");
                    }
                    else
                    {
                        throw new Exception(apiResponseObject.Exception);
                    }
                }
                else
                {
                    log.Error("Error StatusCode:" + response.StatusCode.ToString() + " - " + response.ReasonPhrase);
                    throw new Exception(response.StatusCode.ToString());
                }
            }
        }
    }
}

MVCApplicationFramework.WebUI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCApplicationFramework.WebUI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    CodeArray Technologies Pvt. Ltd.<br />
    Office No. 813, Dhamji Shamji Business Galleria<br />
    L.B.S. Marg, Kanjurmarg West<br />
    Mumbai - 400078 <br />
    Tel: +91 22 25770020
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVCApplicationFramework.WebUI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MVCApplicationFramework.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CA MVC App Framework</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CA MVC App Framework", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("User Manager", "Index", "UserManager")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CA MVC App Framework</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MVCApplicationFramework.WebUI/Views/UserManager/Edit.cshtml
@model  MVCApplicationFramework.Entities.User
@{
    ViewBag.Title = "Edit";
}

<h2>Edit User</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.LoginName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LoginName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MiddleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ContactNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactNumber, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        @*<div class="form-group">
            @Html.LabelFor(model => model.Roles, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.DropDownListFor(model => model.Roles, ViewBag.RolesList as List<SelectListItem>, "-- Role --")
        </div>*@
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVCApplicationFramework.WebUI/Views/UserManager/Index.cshtml
@model  IList<MVCApplicationFramework.Entities.User>
@{
    ViewBag.Title = "Index";
}

<h2>User's List</h2>

<table id="datatables-UserList" class="table table-bordered" style="table-layout: fixed; align-content:center">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Login Name
            </th>
            <th>
                First Name
            </th>
            <th>
                Last Name
            </th>
        </tr>
    </thead>
    <tbody style="align-content:center">

        @if (Model.Count > 0)
        {
            foreach (var item in Model)
            {
                <tr style="align-content:center">
                    <td class="col-md-1">
                        @Html.ActionLink(Convert.ToString(@item.ID), "Edit", "UserManager", new { Id = @item.ID }, null)
                    </td>
                    <td class="col-md-1">
                        @item.LoginName 
                    </td>
                    <td class="col-md-1">
                        @item.FirstName
                    </td>
                    <td class="col-md-1">
                        @item.LastName
                    </td>
                </tr>
            }
        }
        else
        {
            <tr id="trNoRecord">
                <td colspan="6" class="text-center">No record found. </td>
            </tr>
        }


    </tbody>
</table>